apiVersion: v1
kind: ConfigMap
metadata:
  name: immutable-checker.default.svc
  namespace: default
data:
  policy.conf: |
    ingress.metadata.annotations["kubernetes.io/ingress.global-static-ip-name"]
